@baseUrl = http://sfapi.innovix-solutions.net

###
GET {{baseUrl}}/api/website/slider HTTP/1.1

###
GET {{baseUrl}}/api/list/delivery/carrier HTTP/1.1

###
GET {{baseUrl}}/api/product/categories HTTP/1.1

###
GET {{baseUrl}}/api/ecommerce/contactus HTTP/1.1