// SENDSIGNIN
export const SENDSIGNIN_REQUEST = 'SENDSIGNIN_REQUEST'
export const SENDSIGNIN_ERROR = 'SENDSIGNIN_ERROR'
export const SENDSIGNIN_SUCCESS = 'SENDSIGNIN_SUCCESS'

// SENDSIGNUP
export const SENDSIGNUP_REQUEST = 'SENDSIGNUP_REQUEST'
export const SENDSIGNUP_ERROR = 'SENDSIGNUP_ERROR'
export const SENDSIGNUP_SUCCESS = 'SENDSIGNUP_SUCCESS'

// SENDOTP
export const SENDOTP_REQUEST = 'SENDOTP_REQUEST'
export const SENDOTP_ERROR= 'SENDOTP_ERROR'
export const SENDOTP_SUCCESS= 'SENDOTP_SUCCESS'

// USERCHECK AND RESENDTOP
export const USERCHECK_REQUEST= 'USERCHECK_REQUEST'
export const USERCHECK_ERROR= 'USERCHECK_ERROR'
export const USERCHECK_SUCCESS= 'USERCHECK_SUCCESS'

// resetPassword
export const RESETPASSWORD_REQUEST= 'RESETPASSWORD_REQUEST'
export const RESETPASSWORD_ERROR= 'RESETPASSWORD_ERROR'
export const RESETPASSWORD_SUCCESS= 'RESETPASSWORD_SUCCESS'

// getPROFILE
export const GETPROFILE_REQUEST= 'GETPROFILE_REQUEST'
export const GETPROFILE_ERROR= 'GETPROFILE_ERROR'
export const GETPROFILE_SUCCESS= 'GETPROFILE_SUCCESS'

// sentPROFILE
export const UPDATEPROFILE_REQUEST= 'UPDATEPROFILE_REQUEST'
export const UPDATEPROFILE_ERROR= 'UPDATEPROFILE_ERROR'
export const UPDATEPROFILE_SUCCESS= 'UPDATEPROFILE_SUCCESS'

// getORDER
export const GETORDER_REQUEST= 'GETORDER_REQUEST'
export const GETORDER_ERROR= 'GETORDER_ERROR'
export const GETORDER_SUCCESS= 'GETORDER_SUCCESS'

// getORDERById
export const GETORDERBYID_REQUEST= 'GETORDERBYID_REQUEST'
export const GETORDERBYID_ERROR= 'GETORDERBYID_ERROR'
export const GETORDERBYID_SUCCESS= 'GETORDERBYID_SUCCESS'

// about
export const GETABOUTUS_REQUEST = 'GETABOUTUS_REQUEST'
export const GETABOUTUS_ERROR = 'GETABOUTUS_ERROR'
export const GETABOUTUS_SUCCESS = 'GETABOUTUS_SUCCESS'

// transition
export const GETTRANSLATION_REQUEST = 'GETTRANSLATION_REQUEST'
export const GETTRANSLATION_ERROR = 'GETTRANSLATION_ERROR'
export const GETTRANSLATION_SUCCESS = 'GETTRANSLATION_SUCCESS'

// contact
export const GETCONTACTUS_REQUEST = 'GETCONTACTUS_REQUEST'
export const GETCONTACTUS_ERROR = 'GETCONTACTUS_ERROR'
export const GETCONTACTUS_SUCCESS = 'GETCONTACTUS_SUCCESS'

export const SENTCONTACTUS_REQUEST = 'SENTCONTACTUS_REQUEST'
export const SENTCONTACTUS_ERROR = 'SENTCONTACTUS_ERROR'
export const SENTCONTACTUS_SUCCESS = 'SENTCONTACTUS_SUCCESS'

// product
export const GETPRODUCT_REQUEST = 'GETPRODUCT_REQUEST'
export const GETPRODUCT_ERROR = 'GETPRODUCT_ERROR'
export const GETPRODUCT_SUCCESS = 'GETPRODUCT_SUCCESS'

// product by id
export const GETPRODUCTBYID_REQUEST = 'GETPRODUCTBYID_REQUEST'
export const GETPRODUCTBYID_ERROR = 'GETPRODUCTBYID_ERROR'
export const GETPRODUCTBYID_SUCCESS = 'GETPRODUCTBYID_SUCCESS'

// product by category
export const GETPRODUCTBYCATEGORY_REQUEST = 'GETPRODUCTBYCATEGORY_REQUEST'
export const GETPRODUCTBYCATEGORY_ERROR = 'GETPRODUCTBYCATEGORY_ERROR'
export const GETPRODUCTBYCATEGORY_SUCCESS = 'GETPRODUCTBYCATEGORY_SUCCESS'

// product brand
export const GETPRODUCTBRAND_REQUEST = 'GETPRODUCTBRAND_REQUEST'
export const GETPRODUCTBRAND_ERROR = 'GETPRODUCTBRAND_ERROR'
export const GETPRODUCTBRAND_SUCCESS = 'GETPRODUCTBRAND_SUCCESS'